# coding=utf-8
# Generated by Django 1.11.28 on 2020-07-09 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tablet", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("category", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Workstation",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("products", models.ManyToManyField(to="tablet.Product")),
            ],
        ),
        migrations.AddField(
            model_name="tablet", name="workstations", field=models.ManyToManyField(to="tablet.Workstation"),
        ),
    ]
