repos:
  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
      - id: check-ast
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: end-of-file-fixer
        exclude_types: [svg, css, html, less, javascript, json, coffee, map, markdown]
      # Унификация encodging в проекте
      - id: fix-encoding-pragma
        args: [--pragma=# coding=utf-8]
  - repo: local
    hooks:
      - id: black
        name: black
        entry: venv3/bin/black
        language: python
        types: [python]
        args: []
        require_serial: false
        additional_dependencies: []
      # isort из репки pre-commit неправильно работает
      - id: isort
        name: isort
        entry: venv/bin/isort
        language: python
        types: [python]
        args: [-a from __future__ import unicode_literals]
        require_serial: false
        additional_dependencies: []
